# Generated by Django 4.2.2 on 2023-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=80, null=True)),
                ('ativo', models.BooleanField(null=True)),
            ],
        ),
    ]
