# Generated by Django 4.2.2 on 2023-07-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
    ]
