# Generated by Django 4.2.2 on 2023-07-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_remove_colaborador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
