# Generated by Django 4.2.2 on 2023-07-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0009_alter_produto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, null=True)),
                ('produtos', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
