# Generated by Django 4.2.2 on 2023-07-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
