# Generated by Django 4.2.2 on 2023-07-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_tipo_produto_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
    ]
