# Generated by Django 4.2.2 on 2023-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_delete_tipo_remove_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(null=True),
        ),
    ]
