# Generated by Django 4.2.2 on 2023-07-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_tipo_alter_produto_ativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
