# Generated by Django 4.2.2 on 2023-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_delete_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Salgado', 'Salgado'), ('Doce', 'Doce'), ('Bebida', 'Bebida'), ('Camiseta', 'Camiseta'), ('Ingresso', 'Ingresso')], max_length=20, null=True),
        ),
    ]
