# Generated by Django 4.2.2 on 2023-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Alimento', 'Alimento'), ('Bebida', 'Bebida'), ('Camiseta', 'Camiseta'), ('Ingresso', 'Ingresso')], max_length=20, null=True),
        ),
    ]
