# Generated by Django 4.2.2 on 2023-06-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='produtos',
        ),
    ]
