# Generated by Django 4.2.2 on 2023-06-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_codigo_barras'),
        ('compra', '0002_remove_compra_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.FloatField(null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='compra.Item_Compra', to='produtos.produto'),
        ),
    ]
